"""TCGplayer packing-slip PDF parsing (Section 8 order intake).

TCGplayer's packing slips are generated by PDFsharp as *text* PDFs — embedded
Arial subsets with ``/Encoding /WinAnsiEncoding`` and no images anywhere — so
every field is recoverable byte-exact and no OCR is involved. That matters
because these numbers land in the P&L: an OCR'd price is a guess, a decoded
string is the price.

Two wrinkles the extraction has to handle:

1. **PDFsharp emits one ``Tj`` per word and breaks words at hyphens**, so
   "Middle-earth" arrives as ``(Middle-) (earth)`` and would naively rejoin as
   "Middle- earth". The fix is to measure: each font's ``/Widths`` array gives
   the exact advance of the preceding string, so the gap between where a string
   *ends* and the next one *begins* is either ~0 (an artifact — join) or a full
   space width (a real space). On real slips artifact gaps run <=0.05pt against
   2.78pt for a 10pt space, so the test has a ~50x margin and is exact rather
   than heuristic. It does have to use the *right* font's widths per string,
   which is why glyph metrics are resolved per page resource name.

2. **A single order can span pages.** The item table doesn't continue, but the
   trailing boilerplate does, so pages are grouped by order number and the
   fields are taken from whichever page carried them.

The parser is deliberately dependency-free (``re`` + ``zlib``) — adding a PDF
library to read one vendor's fixed template would be a much larger surface than
the ~200 lines it replaces.
"""
import math
import re
import zlib

BACKSLASH = chr(92).encode()
IDENT = (1.0, 0.0, 0.0, 1.0, 0.0, 0.0)

# Content-stream tokenizer: literal/hex strings, numbers, names, array
# delimiters, operators. Enough of the grammar to walk text-positioning ops.
_TOKEN = re.compile(rb"""
    \((?:\\.|[^\\()])*\)
  | <[0-9A-Fa-f\s]*>
  | [-+]?[0-9]*\.?[0-9]+
  | /[^\s/\[\]<>(){}]+
  | \[ | \]
  | [A-Za-z'"*][A-Za-z0-9'"*]*
""", re.X)

_ESCAPES = {b'n': 10, b'r': 13, b't': 9, b'b': 8, b'f': 12}

# A WinAnsi space is 277/1000 em in Arial; a real word gap is one of those.
_SPACE_EM = 0.277


class SlipParseError(ValueError):
    """The upload isn't a packing-slip PDF we can read."""


# --- PDF object plumbing -----------------------------------------------------

def _objects(data: bytes) -> dict[int, bytes]:
    return {int(m.group(1)): m.group(2) for m in
            re.finditer(rb'(?<![0-9])(\d+)\s+0\s+obj(.*?)endobj', data, re.S)}


def _stream(body: bytes) -> bytes:
    m = re.search(rb'stream\r?\n(.*?)\s*endstream', body, re.S)
    if not m:
        return b''
    raw = m.group(1)
    if b'FlateDecode' in body[:m.start()]:
        try:
            return zlib.decompress(raw)
        except zlib.error:
            return b''
    return raw


def _font_widths(objs: dict[int, bytes]) -> dict[int, list[float]]:
    """obj number -> /Widths array, for every font dict that has one."""
    out = {}
    for num, body in objs.items():
        head = body.split(b'stream')[0]
        m = re.search(rb'/Widths\s*\[([^\]]*)\]', head)
        if m and b'/Font' in head:
            out[num] = [float(x) for x in m.group(1).split()]
    return out


def _pages(data: bytes) -> list[tuple[bytes, dict[str, list[float]]]]:
    """[(content stream, {resource name: glyph widths})] in document order."""
    objs = _objects(data)
    widths = _font_widths(objs)
    out = []
    for num, body in sorted(objs.items()):
        head = body.split(b'stream')[0]
        if not re.search(rb'/Type\s*/Page[^s]', head):
            continue
        ref = re.search(rb'/Contents\s+(\d+)\s+0\s+R', head)
        if not ref:
            continue
        fonts = {}
        block = re.search(rb'/Font\s*<<([^>]*)>>', head)
        if block:
            for name, obj in re.findall(rb'/(\S+)\s+(\d+)\s+0\s+R', block.group(1)):
                if int(obj) in widths:
                    fonts['/' + name.decode()] = widths[int(obj)]
        out.append((_stream(objs[int(ref.group(1))]), fonts))
    return out


def _unescape(tok: bytes) -> str:
    """PDF literal string -> text. Slips are WinAnsi, which is cp1252."""
    body = tok[1:-1]
    out = bytearray()
    i = 0
    while i < len(body):
        if body[i:i + 1] != BACKSLASH:
            out += body[i:i + 1]
            i += 1
            continue
        nxt = body[i + 1:i + 2]
        if nxt in _ESCAPES:
            out.append(_ESCAPES[nxt])
            i += 2
        elif nxt.isdigit():
            j, digits = i + 1, b''
            while j < len(body) and len(digits) < 3 and body[j:j + 1].isdigit():
                digits += body[j:j + 1]
                j += 1
            out.append(int(digits, 8) & 0xFF)
            i = j
        elif nxt == b'\n':
            i += 2
        else:
            out += nxt
            i += 2
    return out.decode('cp1252', 'replace')


def _mul(a, b):
    """3x2 affine matrix product (PDF matrix convention)."""
    return (a[0] * b[0] + a[1] * b[2], a[0] * b[1] + a[1] * b[3],
            a[2] * b[0] + a[3] * b[2], a[2] * b[1] + a[3] * b[3],
            a[4] * b[0] + a[5] * b[2] + b[4], a[4] * b[1] + a[5] * b[3] + b[5])


def _walk(content: bytes) -> tuple[list[dict], list[tuple]]:
    """Interpret a content stream -> (placed strings, filled rectangles).

    Strings carry page-space x/y, effective font size and resource name.
    Rectangles come from ``re`` and give the table's exact column boundaries.
    """
    ctm, stack = IDENT, []
    tm = line = IDENT
    size, font = 10.0, None
    strings, rects, ops = [], [], []
    for tok in _TOKEN.finditer(content):
        t = tok.group(0)
        head = t[:1]
        if head in b'0123456789+-.':
            try:
                ops.append(float(t))
                continue
            except ValueError:
                pass
        if head in (b'(', b'<', b'/') or t in (b'[', b']'):
            ops.append(t)
            continue
        nums = [o for o in ops if isinstance(o, float)]
        names = [o for o in ops if isinstance(o, bytes) and o[:1] == b'/']
        if t == b'q':
            stack.append(ctm)
        elif t == b'Q':
            ctm = stack.pop() if stack else IDENT
        elif t == b'cm' and len(nums) >= 6:
            ctm = _mul(tuple(nums[-6:]), ctm)
        elif t == b're' and len(nums) >= 4:
            x, y, w, h = nums[-4:]
            p = _mul((1.0, 0.0, 0.0, 1.0, x, y), ctm)
            rects.append((p[4], p[5], w, h))
        elif t == b'BT':
            tm = line = IDENT
        elif t == b'Tf':
            if nums:
                size = nums[-1]
            if names:
                font = names[-1].decode()
        elif t in (b'Td', b'TD') and len(nums) >= 2:
            line = _mul((1.0, 0.0, 0.0, 1.0, nums[-2], nums[-1]), line)
            tm = line
        elif t == b'Tm' and len(nums) >= 6:
            tm = line = tuple(nums[-6:])
        elif t == b'T*':
            line = _mul((1.0, 0.0, 0.0, 1.0, 0.0, -size), line)
            tm = line
        elif t in (b'Tj', b"'", b'"', b'TJ'):
            for o in ops:
                if isinstance(o, bytes) and o[:1] == b'(':
                    text = _unescape(o)
                    if text.strip():
                        m = _mul(tm, ctm)
                        scale = math.hypot(m[0], m[1]) or 1.0
                        strings.append({'x': m[4], 'y': m[5], 's': text,
                                        'size': size * scale, 'font': font})
        ops = []
    return strings, rects


# --- text reassembly ---------------------------------------------------------

def _advance(text: str, widths: list[float] | None, size: float) -> float:
    if not widths:
        return 0.0
    return sum(widths[min(ord(c), 255)] for c in text) * size / 1000.0


def _join(parts: list[dict], fonts: dict[str, list[float]]) -> str:
    """Rebuild a run of strings, inserting a space only where the glyph advance
    proves there was one (see module docstring)."""
    out, end = '', None
    for p in parts:
        widths = fonts.get(p['font'])
        if end is not None and p['x'] - end > _SPACE_EM * p['size'] * 0.5:
            out += ' '
        out += p['s']
        end = p['x'] + _advance(p['s'], widths, p['size'])
    return out


def _rows(strings: list[dict], fonts: dict, ytol: float = 2.5) -> list[dict]:
    """Group placed strings into visual lines, top-to-bottom, left-to-right."""
    rows: list[dict] = []
    for p in sorted(strings, key=lambda i: (-i['y'], i['x'])):
        for r in rows:
            if abs(r['y'] - p['y']) <= ytol:
                r['parts'].append(p)
                break
        else:
            rows.append({'y': p['y'], 'parts': [p]})
    for r in rows:
        r['parts'].sort(key=lambda p: p['x'])
        r['text'] = _join(r['parts'], fonts)
    return rows


# --- slip field parsing -----------------------------------------------------

_CITY_ST_ZIP = re.compile(r'^(.*?),\s*([A-Z]{2})\s+(\d{5})(?:-\d{4})?$')
_MONEY = re.compile(r'^\$([\d,]+\.\d{2})$')
_ORDER_DATE = re.compile(r'Order Date:\s*(\d{2}/\d{2}/\d{4})')
_BUYER = re.compile(r'Buyer Name:\s*(.+?)$')
_PAGE_OF = re.compile(r'Page\s+(\d+)\s+of\s+(\d+)')

# "{game} - {set} - {card name} - #{number} - {rarity} - {condition}".
# Anchored from the right because the tail is fixed-arity while set and card
# names both contain " - ", colons, commas and parentheses.
_DESCRIPTION = re.compile(
    r'^(?P<head>.+?)\s+-\s+#(?P<number>\S+)\s+-\s+(?P<rarity>\S+)\s+-\s+'
    r'(?P<condition>.+?)$')

# Pre-numbering-era sets (Beta, Antiquities, Legends, ...) predate TCGplayer's
# on-card numbering scheme, so the slip prints no "#number" segment at all:
# "{game} - {set} - {card name} - {rarity} - {condition}". Without the "#" to
# anchor on, head has to be greedy rather than lazy — greedy backtracking finds
# the *rightmost* "- {single token} - " split, which lands on the rarity/
# condition boundary even when the set or card name itself contains " - ".
# (A lazy head plus an optional number group would instead stop at the first,
# usually wrong, split.)
_DESCRIPTION_NO_NUMBER = re.compile(
    r'^(?P<head>.+)\s+-\s+(?P<rarity>\S+)\s+-\s+(?P<condition>.+)$')

# TCGplayer appends the finish to the condition ("Near Mint Foil"), so printing
# is recovered by stripping a known finish suffix off the condition cell.
_FINISH_SUFFIXES = {
    'Reverse Holofoil': 'reverse_holo',
    'Etched Foil': 'foil',
    'Foil Etched': 'foil',
    'Holofoil': 'holo',
    'Foil': 'foil',
}


def _money(text: str) -> float | None:
    m = _MONEY.match(text.strip())
    return float(m.group(1).replace(',', '')) if m else None


def _columns(rows: list[dict], rects: list[tuple]) -> tuple[dict | None, list]:
    """The item table's header row and its exact column x-ranges.

    Boundaries come from the drawn header cells rather than from where the
    header *labels* happen to start, because "Total Price" repeats the word
    "Price" and label positions don't mark cell edges.
    """
    header = next((r for r in rows
                   if r['text'].startswith('Quantity Description')), None)
    if not header:
        return None, []
    cells = sorted(((x, x + w) for (x, y, w, h) in rects
                    if abs(y + h / 2 - (header['y'] + 5)) < 12 and 40 < w < 400),
                   key=lambda c: c[0])
    return header, cells


def split_description(description: str) -> dict:
    """Break a slip line's description into matchable fields.

    Returns ``parse_ok: False`` with the raw text when the shape is unfamiliar,
    so an odd line is flagged for review instead of silently mis-parsed.
    """
    m = _DESCRIPTION.match(description)
    if m:
        number = m.group('number')
    else:
        m = _DESCRIPTION_NO_NUMBER.match(description)
        if not m:
            return {'parse_ok': False, 'raw': description}
        number = None
    parts = m.group('head').split(' - ')
    condition = m.group('condition').strip()
    printing = 'normal'
    for suffix, canonical in sorted(_FINISH_SUFFIXES.items(),
                                    key=lambda kv: -len(kv[0])):
        if condition.endswith(' ' + suffix):
            condition = condition[:-(len(suffix) + 1)].strip()
            printing = canonical
            break
    return {
        'parse_ok': True,
        'game_label': parts[0] if parts else '',
        'set_name': parts[1] if len(parts) > 1 else '',
        'card_name': ' - '.join(parts[2:]) if len(parts) > 2 else '',
        'collector_number': number,
        'rarity_letter': m.group('rarity'),
        'condition_label': condition,
        'printing': printing,
    }


def _parse_page(content: bytes, fonts: dict) -> dict:
    strings, rects = _walk(content)
    rows = _rows(strings, fonts)
    page: dict = {'items': []}

    for r in rows:
        text = r['text']
        if text.startswith('Order Number:') and 'order_number' not in page:
            rest = text.split('Order Number:', 1)[1].strip()
            page['order_number'] = re.split(r'\s+Page\b', rest)[0].strip()
        m = _ORDER_DATE.search(text)
        if m:
            page['order_date'] = m.group(1)
        m = _BUYER.search(text)
        if m:
            page['buyer_name'] = m.group(1).strip()
        m = _PAGE_OF.search(text)
        if m:
            page['page_of'] = [int(m.group(1)), int(m.group(2))]

    # Ship-To block sits in the left margin above the dashed divider. Find the
    # "CITY, ST ZIP" line by shape — an apartment/unit line can precede it, so
    # counting lines from the top would pick the wrong one.
    for r in rows:
        if r['parts'][0]['x'] < 40 and r['y'] > 600:
            m = _CITY_ST_ZIP.match(r['text'].strip())
            if m:
                page['ship_city'] = m.group(1).strip()
                page['ship_state'] = m.group(2)
                page['ship_postal_code'] = m.group(3)
                break

    header, cells = _columns(rows, rects)
    if not header or len(cells) < 4:
        return page  # continuation page: boilerplate only, no item table
    (q0, q1), (d0, d1), (p0, p1), (t0, t1) = cells[:4]
    current = None
    for r in rows:
        if r['y'] >= header['y']:
            continue

        def cell(lo, hi, parts=r['parts']):
            return [p for p in parts if lo - 2 <= p['x'] < hi + 2]

        qty, desc = cell(q0, q1), cell(d0, d1)
        price, total = cell(p0, p1), cell(t0, t1)
        if not (qty or desc or price or total):
            continue
        qty_text = _join(qty, fonts).strip()
        desc_text = _join(desc, fonts).strip()
        # The "N  Total  $X" row closes the table. "Total" is rendered in the
        # description column, so it's matched by value, not by an empty cell.
        if qty_text.isdigit() and desc_text == 'Total':
            page['quantity_total'] = int(qty_text)
            page['item_total'] = (_money(_join(total, fonts).strip())
                                  or _money(_join(price, fonts).strip()))
            break
        if qty_text.isdigit() and desc:
            current = {'quantity': int(qty_text), 'chunks': [desc_text],
                       'unit_price': _money(_join(price, fonts).strip()),
                       'line_total': _money(_join(total, fonts).strip())}
            page['items'].append(current)
        elif current is not None and desc and not qty:
            current['chunks'].append(desc_text)  # wrapped description
        elif current is not None and not desc:
            break
    for item in page['items']:
        item['description'] = ' '.join(item.pop('chunks')).strip()
    return page


_MERGE_FIELDS = ('order_date', 'buyer_name', 'ship_city', 'ship_state',
                 'ship_postal_code', 'item_total', 'quantity_total')


def parse_packing_slips(data: bytes) -> list[dict]:
    """Parse a packing-slip PDF into one dict per order.

    Pages are grouped by order number, so a slip that spills its trailing
    boilerplate onto a second page yields one order, not two.

    Each order carries ``lines`` (quantity, prices, and the split description
    fields), the printed ``item_total`` / ``quantity_total``, and the buyer's
    city/state. The printed totals are kept rather than discarded because they
    independently confirm the parse: if the summed lines don't match what
    TCGplayer printed, something was misread and the order should be reviewed.
    """
    if not data[:5] == b'%PDF-':
        raise SlipParseError("not a PDF file")
    pages = _pages(data)
    if not pages:
        raise SlipParseError("no readable pages in the PDF")
    orders: dict[str, dict] = {}
    for content, fonts in pages:
        page = _parse_page(content, fonts)
        number = page.get('order_number')
        if not number:
            continue
        order = orders.setdefault(number, {'order_number': number,
                                           'lines': [], 'page_count': 0})
        order['page_count'] += 1
        for field in _MERGE_FIELDS:
            if page.get(field) is not None and order.get(field) is None:
                order[field] = page[field]
        for item in page['items']:
            item.update(split_description(item['description']))
            order['lines'].append(item)
    if not orders:
        raise SlipParseError(
            "no order numbers found — is this a TCGplayer packing slip PDF?")
    return list(orders.values())


def reconciles(order: dict) -> bool:
    """Do the parsed lines agree with the totals TCGplayer printed?"""
    printed_total = order.get('item_total')
    printed_qty = order.get('quantity_total')
    if printed_total is None or printed_qty is None:
        return False
    lines = order.get('lines') or []
    qty = sum(l.get('quantity') or 0 for l in lines)
    total = round(sum((l.get('line_total') or 0.0) for l in lines), 2)
    return qty == printed_qty and abs(total - printed_total) < 0.005
